#! /bin/sh

xrandr --output HDMI-0 --primary --output DVI-1 --left-of HDMI-0

xsetroot -cursor_name left_ptr

bspc monitor HDMI-0 -s DVI-1

#compton &
sxhkd -m 1 &
dunst &
polybar top &

xset b off

bspc monitor HDMI-0 -d I II III
bspc monitor DVI-1 -d I II III

bspc config border_width         2
bspc config window_gap       5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Termite:float state=floating
bspc rule -a Zathura state=tiled

bspc config normal_border_color           "#6C6C6C"
bspc config focused_border_color          "#BCBCBC"
bspc config presel_feedback_color "#5F5F87"
