#! /bin/sh

xrandr --output DP-1 --primary --pos 2400x0 --output HDMI-1 --pos 0x405 --scale 1.25 --fb 6240x2160

xsetroot -cursor_name left_ptr
feh --bg-fill /home/marvin/Pictures/firewatch_wallpaper.jpg

wmname LG3D
bspc monitor DP-1 -s HDMI-1

sxhkd -m 1 &
dunst &
polybar top &

xset b off

bspc monitor DP-1 -d I II III
bspc monitor HDMI-1 -d I II III

bspc config border_width         2
bspc config window_gap       5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Termite:float state=floating
bspc rule -a Zathura state=tiled

bspc config normal_border_color           "#262626"
bspc config focused_border_color          "#5f875f"
bspc config presel_feedback_color "#5f875f"
