#! /bin/sh

xrandr --output HDMI-0 --primary --output DVI-1 --left-of HDMI-0

xsetroot -cursor_name left_ptr
feh --bg-fill /home/marvin/Pictures/forest_wallpaper.jpg

bspc monitor HDMI-0 -s DVI-1

picom &
sxhkd -m 1 &
dunst &
polybar top &

xset b off

bspc monitor HDMI-0 -d I II III
bspc monitor DVI-1 -d I II III

bspc config border_width         2
bspc config window_gap       5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Termite:float state=floating
bspc rule -a Zathura state=tiled

bspc config normal_border_color           "#262626"
bspc config focused_border_color          "#5f875f"
bspc config presel_feedback_color "#5f875f"
