#! /bin/sh
feh --bg-scale ~/.wallpaper/wallpaper.jpg

polybar top &
nm-applet &
pasystray &

color=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
color2=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)

bspc monitor DVI-0 -n left
bspc monitor HDMI-0 -n right

bspc monitor left -d 1 2 3
bspc monitor right -d 4 5 6

xsetroot -cursor_name left_ptr

bspc config border_width   2
bspc config window_gap     6
bspc config focused_border_color "#$color"
bspc config normal_border_color "#$color2"

bspc config top_padding 0
bspc config -m primary top_padding 28

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

bspc rule -a Zathura state=tiled
