#! /bin/sh

sxhkd -m 1 &
compton &	
xautolock -detectsleep &
dunst -config ~/.config/dunst/dunstrc &
MONITOR=$(xrandr -q | grep primary | awk '{print $1}') polybar top &
nm-applet &
pasystray &

bspc monitor DVI-0 -n left
bspc monitor HDMI-0 -n right

bspc config border_width   1
bspc config window_gap     6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

xset s 300
xset +dpms
xset dpms 600 600 0

bspc config top_padding 0
bspc config -m primary top_padding 22

bspc monitor left -d 1 2 3
bspc monitor right -d 4 5 6
